databases:
  - name: blog-database
    plan: free
    databaseName: blog-database
    user: adacorp 

services:
  - type: web
    plan: free
    name: blog
    runtime: python
    buildCommand: './blog/build.sh'
    startCommand: 'python -m gunicorn blog/blog.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key : RENDER
        value: 1